version: '3'
services:
  servicecontroladorusuario:
    build: service-controlador-usuario/
    links:
      - servicecadastrousuario
    ports:
      - "8080:8080"
  servicecadastrousuario:
    build: service-cadastro-usuario/
    ports:
      - "9000:8080"
  servicecontroladoratividades:
    build: service-controlador-atividades/
    links:
      - servicecadastroatividade
    ports:
      - "9020:8080"
  servicecadastroatividade:
    build: service-cadastro-atividade/
    ports:
      - "9010:8080"
