version: '3'
services:
  servicecontroladorusuario:
    build: service-controlador-usuario/
    links:
      - servicecadastrousuario
    ports:
      - "8080:8080"
  servicecadastrousuario:
    build: service-cadastro-usuario/
    ports:
      - "9000:8080"
